name: Deploy to Firebase Hosting

on:
  push:
    workflow_dispatch:    # PR時はプレビューURL

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build (Angular)
        run: npm run build --if-present

      # PR → プレビュー（preview channel）
      - name: Deploy Preview (on PR)
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KENSYU10121 }}
          projectId: kensyu10121
          expires: 7d

      # main へ push → 本番（live）
      - name: Deploy Production (on main)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KENSYU10121 }}
          projectId: kensyu10121
          channelId: live
